import dotenv from 'dotenv'
dotenv.config()

export const env = {
  PORT: process.env.PORT,
  HOSTNAME: process.env.HOSTNAME,
  CLIENT_HOSTNAME: process.env.CLIENT_HOSTNAME,
  DATABASE_URL: process.env.DATABASE_URL,
  DATABASE_NAME: process.env.DATABASE_NAME,
  JWT_SECRET: process.env.JWT_SECRET,
  ACCESS_TOKEN_EXPIRATION: process.env.ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION: process.env.REFRESH_TOKEN_EXPIRATION,
  FORGOT_PASSWORD_TOKEN_EXPIRATION: process.env.FORGOT_PASSWORD_TOKEN_EXPIRATION,
  EMAIL_VALIDATOR_TOKEN_EXPIRATION: process.env.EMAIL_VALIDATOR_TOKEN_EXPIRATION,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASSWORD: process.env.MAIL_PASSWORD,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI
}
